version: "3.8"

services:
  analysis:
    build: .
    volumes:
      - .:/app
      - ../results:/app/results
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
