version: "3.8"

services:
  analysis:
    build: .
    volumes:
      - ./..:/workspace
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
